services:
  app:
    image: goldencrown-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7194:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=GoldenCrownDB;User Id=sa;Password=Your_Strong_Password123!;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Your_Strong_Password123! 
    ports:
      - "1433:1433" 
    volumes:
      - sql_data:/var/opt/mssql 

volumes:
  sql_data: